### ISSUE TITLE
keepANSI is not defined

### ISSUE THREAD

**Issue by akkenoth** [Tjatse/pm2-gui#29]
When opening log of application that was just removed:
```
/usr/lib/node_modules/pm2-gui/lib/mon.js:227
      msg  : keepANSI ? chalk.red(err.message) : '<span style="color: #ff0000"
             ^
ReferenceError: keepANSI is not defined
    at Monitor.emitError (/usr/lib/node_modules/pm2-gui/lib/mon.js:227:14)
    at Monitor.<anonymous> (/usr/lib/node_modules/pm2-gui/lib/mon.js:293:26)
    at /usr/lib/node_modules/pm2-gui/lib/pm.js:227:14
    at /usr/lib/node_modules/pm2-gui/lib/pm.js:141:14
    at /usr/lib/node_modules/pm2-gui/lib/pm.js:104:16
    at /usr/lib/node_modules/pm2-gui/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2-gui/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
    at Parser._write (/usr/lib/node_modules/pm2-gui/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

It seems that the flag is simply missing from `emitError()` declaration in `socket.on('tail', ...)`.

**Comment by Tjatse** [comment]
Fixed @0.1.2!
