### ISSUE TITLE
Unable to launch the gui-web

### ISSUE THREAD

**Issue by anil1712** [Tjatse/pm2-gui#44]
Hi,

I did exactly as per the DOC but getting this exception in terminal while running below command.
`./pm2-gui start`

```
/gui/pm2-gui/libs/monitor.js:353
      let error
      ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/sentora/hostdata/zadmin/public_html/gui/pm2-gui/libs/daemon.js:10:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[WARN] â stopped
```
@Tjatse Please let me know if am I doing something wrong.

Thanks,

**Comment by Tjatse** [comment]
Hi@anil1712, Just try the lastest stable pack from npm but not `master` branch from github, e.g.:

```
npm i pm2-gui@0.1.4 -g
```
