### ISSUE TITLE
Cannot start although pm2 is running: .pm2\conf.js does not exist

### ISSUE THREAD

**Issue by jdcrecur** [Tjatse/pm2-gui#70]
Awesome tool, works fine on Ubuntu.. but cannot get running on a windows machine :(

OS
Windows10

Node
10.1.10

npm
5.6.0

The error when starting the packaged script:

```
C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui>node pm2-gui.js
[WARN] Can not load PM2 config, the file "C:\Users\me\.pm2\conf.js" does not exist or empty, fallback to auto-load by pm2 home.
C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\lib\monitor.js:156
      throw new Error(fbMsg + 'Unfortunately ' + (val || prop) + ' can not found, please makesure that your pm2 is running and the home path is correct.')
      ^

Error: Can not load PM2 config, the file "C:\Users\me\.pm2\conf.js" does not exist or empty, fallback to auto-load by pm2 home. Unfortunately C:\Users\me\.pm2\rpc.sock can not found, please makesure that your pm2 is running and the home path is correct.
    at C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\lib\monitor.js:156:13
    at Array.forEach (<anonymous>)
    at Monitor._init (C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\lib\monitor.js:153:28)
    at new Monitor (C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\lib\monitor.js:30:8)
    at Monitor (C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\lib\monitor.js:26:12)
    at slave (C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\pm2-gui.js:163:17)
    at startWebServer (C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\pm2-gui.js:48:17)
    at Object.<anonymous> (C:\Users\me\Downloads\pm2-monitor\node_modules\pm2-gui\pm2-gui.js:24:7)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
```

Is this package just not supported on windows10?

**Comment by Tjatse** [comment]
pm2 based on `axon`'s unix socket, i.e.: `unix://some/path/conn.sock`, this is not very friendly towards Windows, ;)
