### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by Bernard04** [Tjatse/pm2-gui#80]
[INFO] Starting...
[WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
fs.js:135
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1181:14)
    at Object.fork (/usr/lib/node_modules/pm2-gui/lib/daemon.js:121:12)
    at start (/usr/lib/node_modules/pm2-gui/lib/daemon.js:47:30)
    at /usr/lib/node_modules/pm2-gui/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/usr/lib/node_modules/pm2-gui/node_modules/async/lib/async.js:262:13)
    at processImmediate (timers.js:632:19)
[WARN] ✘ stopped

**Comment by RedSparr0w** [comment]
Also getting this same problem from the latest npm version,
It launches if I install from the repo though:
```cmd
npm install pm2-gui@https://github.com/Tjatse/pm2-gui.git -g
```

**Comment by micookie** [comment]
same problem

**Comment by AviFix** [comment]
same
