### ISSUE TITLE
Custom config starts the process in foreground 

### ISSUE THREAD

**Issue by mc-lovin** [Tjatse/pm2-gui#81]
Running the process with a custom config file starts the process in foreground `sudo pm2-gui start /etc/pm2-gui.ini` and also gives certain errors like

`Can not connect to the server due to Error: xhr poll`

Not sure what is happening but looks like the config file given in the example [here](https://github.com/Tjatse/pm2-gui/blob/master/pm2-gui.ini) has different configuration from the one used actually.

I am using the above custom file with a change in authorization

**Comment by VishwasShashidhar** [comment]
@mc-lovin Set `daemonize = true` in the config file. That'll make the process backgrounded.

**Comment by dmatora** [comment]
it works fine with demonise = false
but when I change it to true it crashes when I try ti start it with
```
pm2-gui start /etc/pm2-gui.ini 
[INFO] Starting...
[WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[INFO] Spawning daemon...
[WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[INFO] Daemonized with pid [1479].
[INFO] Forking slave...
node:internal/validators:440
    throw new ERR_INVALID_ARG_TYPE(name, 'Function', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at maybeCallback (node:fs:189:3)
    at Object.writeFile (node:fs:2266:14)
    at Object.fork (/usr/lib/node_modules/pm2-gui/lib/daemon.js:121:12)
    at start (/usr/lib/node_modules/pm2-gui/lib/daemon.js:47:30)
    at /usr/lib/node_modules/pm2-gui/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/usr/lib/node_modules/pm2-gui/node_modules/async/lib/async.js:262:13)
    at process.processImmediate (node:internal/timers:476:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.17.1
```

**Comment by dmatora** [comment]
`pm2 start "pm2-gui start /etc/pm2-gui.ini"` did the trick for me
